# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BuildLoad < Formula
  desc "build-load - command line tool to create synthetic load for https://github.com/shipwright-io/build"
  homepage "https://github.com/homeport/build-load"
  version "0.6.5"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/homeport/build-load/releases/download/v0.6.5/build-load_0.6.5_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "aa3f80b73dfffb58c21e1aaa18dff81bae419a23914500b5470b7a2f464aafc3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/homeport/build-load/releases/download/v0.6.5/build-load_0.6.5_linux_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "e3812475ea50a21db72e243c831659c94b9a81ce56df931b82db029e3004832a"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/homeport/build-load/releases/download/v0.6.5/build-load_0.6.5_linux_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "cead399b39b0612bd7f158a681b36d7e491e59d1187eebae5fa3db307e7521d0"
  end

  def install
    bin.install "build-load"
  end

  test do
    system "#{bin}/build-load version"
  end
end
