# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BuildLoad < Formula
  desc "build-load - command line tool to create synthetic load for https://github.com/shipwright-io/build"
  homepage "https://github.com/homeport/build-load"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/homeport/build-load/releases/download/v0.7.2/build-load_0.7.2_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "57e7b8bbf2fe592027f0b9098139a57bd99d28629f1e74711f0a8b1382ad7dd2"

      def install
        bin.install "build-load"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/homeport/build-load/releases/download/v0.7.2/build-load_0.7.2_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "bcb522f69780e66bc74aed3126ae4c0c2b6889e2f433e0f3fec1b0fd3447e38c"

      def install
        bin.install "build-load"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/build-load/releases/download/v0.7.2/build-load_0.7.2_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "0d3e6fa04cb41dc226a03790f979285275611af34df3a3fdf2ddc152f6d5d672"

      def install
        bin.install "build-load"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeport/build-load/releases/download/v0.7.2/build-load_0.7.2_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c107843d6084c0bc197cf79802e23837be3f01db00e05a53b6a2f067debcd784"

      def install
        bin.install "build-load"
      end
    end
  end

  test do
    system "#{bin}/build-load version"
  end
end
