# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dyff < Formula
  desc "δyƒƒ /ˈdʏf/ - A diff tool for YAML files, and sometimes JSON"
  homepage "https://github.com/homeport/dyff"
  version "1.4.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/dyff/releases/download/v1.4.6/dyff_1.4.6_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "38ac3ff574054d3524dfabebd1929d4bd32ae808da34c00ccbd14568dbfcd0ff"

      def install
        bin.install "dyff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/homeport/dyff/releases/download/v1.4.6/dyff_1.4.6_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b3b5ad6f3f6665e44b29a6a8cafc7c65be758e9c25f5793429d47650cb572e76"

      def install
        bin.install "dyff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeport/dyff/releases/download/v1.4.6/dyff_1.4.6_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b7915a6327b040376b4dc16e10ecc5ec1bd93fd844aabdfa64279fab8ca4e415"

      def install
        bin.install "dyff"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/homeport/dyff/releases/download/v1.4.6/dyff_1.4.6_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "a3a45e55e3326a897aed33550c74d2e93c53482289536b71385ff4b5e31303db"

      def install
        bin.install "dyff"
      end
    end
  end

  test do
    system "#{bin}/dyff version"
  end
end
