# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gonut < Formula
  desc "gonut - a portable tool to help you verify whether you can push a sample app to a Cloud Foundry"
  homepage "https://github.com/homeport/gonut"
  version "2.0.4"
  license "MIT"

  on_macos do
    url "https://github.com/homeport/gonut/releases/download/v2.0.4/gonut_2.0.4_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "c456e5c7cf76946df4c0b7c1ead4c8fe31bc2207c702d7e83f763034c962a8aa"

    def install
      bin.install "gonut"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/gonut/releases/download/v2.0.4/gonut_2.0.4_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "12938c4c6039d3e4c8a19c88f4efa6bc88c5cb466f1df5729ff49930ab3bd604"

      def install
        bin.install "gonut"
      end
    end
  end

  test do
    system "#{bin}/gonut version"
  end
end
