# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gonut < Formula
  desc "gonut - a portable tool to help you verify whether you can push a sample app to a Cloud Foundry"
  homepage "https://github.com/homeport/gonut"
  version "2.0.3"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/homeport/gonut/releases/download/v2.0.3/gonut_2.0.3_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "d387c94b4b6fb88cdda90fd972c305cb8bad48a6bdd9bf92c0949e24562b7882"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/homeport/gonut/releases/download/v2.0.3/gonut_2.0.3_linux_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "fb5646ac3e01dc0f24176e7b4269d13f2828238d305581ec64069daf21926be7"
  end

  def install
    bin.install "gonut"
  end

  test do
    system "#{bin}/gonut version"
  end
end
