# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Havener < Formula
  desc "/ˈheɪvənə/ - Think of it as a swiss army knife for Kubernetes tasks "
  homepage "https://github.com/homeport/havener"
  version "2.0.6"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/havener/releases/download/v2.0.6/havener_2.0.6_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "fea4c49872bc13a7a667f11bdbd937c7994080fc4eac2837452ac4bc8e48e25d"
    end
    if Hardware::CPU.arm?
      url "https://github.com/homeport/havener/releases/download/v2.0.6/havener_2.0.6_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "7abe83fbe8d9028b0e888aaebafe9ff1e3287660aa53c7f9eebe1312666aaa86"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/havener/releases/download/v2.0.6/havener_2.0.6_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d6cc3e76efc5bd08ec15ed3792ccb4ebffab03a39123f1b2260cab1ac7e149b8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeport/havener/releases/download/v2.0.6/havener_2.0.6_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "9de898c605c81aace7e636597dada7c587ab6bf48d72f5dd367f96f8376577af"
    end
  end

  def install
    bin.install "havener"
  end

  test do
    system "#{bin}/havener version"
  end
end
