# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Havener < Formula
  desc "/ˈheɪvənə/ - Think of it as a swiss army knife for Kubernetes tasks "
  homepage "https://github.com/homeport/havener"
  version "2.0.5"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/havener/releases/download/v2.0.5/havener_2.0.5_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "7c5184f3ddb04e9888de255ecb34a94fb9419dd19aa46532cdc249b846080531"
    end
    if Hardware::CPU.arm?
      url "https://github.com/homeport/havener/releases/download/v2.0.5/havener_2.0.5_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "0bb4c03e0fa48a1ba19984effa35e0a899b0929ee123444d02b312290ab001cb"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/havener/releases/download/v2.0.5/havener_2.0.5_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "041e492d39c0d3399b37d94dd343696a93884be3acf3a70727b87f3aa8c6a65d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/homeport/havener/releases/download/v2.0.5/havener_2.0.5_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "878a422d0e9203b1326c4cff9d5f2e2c6d20448bdaa44ff75ff90d9e5b32ba7d"
    end
  end

  def install
    bin.install "havener"
  end

  test do
    system "#{bin}/havener version"
  end
end
