# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pd < Formula
  desc "pd - command line tool to query PagerDuty for the current on-calls"
  homepage "https://github.com/homeport/pd"
  version "2.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/pd/releases/download/v2.5.2/pd_2.5.2_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "ffb8b7ecade306f1cd98664f097d6f256ab9f31cb50f3811223cb54ee6336a3f"

      def install
        bin.install "pd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/pd/releases/download/v2.5.2/pd_2.5.2_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "31d4e0445db2cf2c02c97ce464746ce33e8e6071a87d1dafe0a58c2d94104fe7"

      def install
        bin.install "pd"
      end
    end
  end

  test do
    system "#{bin}/pd version"
  end
end
