# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pd < Formula
  desc "pd - command line tool to query PagerDuty for the current on-calls"
  homepage "https://github.com/homeport/pd"
  version "2.5.4"
  license "MIT"

  on_macos do
    url "https://github.com/homeport/pd/releases/download/v2.5.4/pd_2.5.4_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "fdbd94bfebf2b55c48ae4aa09f5b50cb51578008bb972914f73b2985b63b7264"

    def install
      bin.install "pd"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/pd/releases/download/v2.5.4/pd_2.5.4_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b1755944e766a36e8907916124bfbb70101a1ebcbb0ffb99308ad24047d46429"

      def install
        bin.install "pd"
      end
    end
  end

  test do
    system "#{bin}/pd version"
  end
end
