# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pd < Formula
  desc "pd - command line tool to query PagerDuty for the current on-calls"
  homepage "https://github.com/homeport/pd"
  version "2.5.1"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/homeport/pd/releases/download/v2.5.1/pd_2.5.1_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "21ab2820fc0580fdc8642556f261bba3f1b587116d7eeaac03076ec13827ff54"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/homeport/pd/releases/download/v2.5.1/pd_2.5.1_linux_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "cf453fff316c9577b886489486b1c46d74526f4d7c65a33057335d0abc8fbed0"
  end

  def install
    bin.install "pd"
  end

  test do
    system "#{bin}/pd --version"
  end
end
