# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PinaGolada < Formula
  desc "pina-golada - a simple asset tool for go, which generates interface implementations that provide files/folders in the final build, without rendering them in the source code themselve"
  homepage "https://github.com/homeport/pina-golada"
  version "1.4.4"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/homeport/pina-golada/releases/download/v1.4.4/pina-golada_1.4.4_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "14517cbce730593e09eef6cde2b434ce9ef665f18566d9910443974a9d6890a0"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/homeport/pina-golada/releases/download/v1.4.4/pina-golada_1.4.4_linux_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "9419f05e3e63c4521dda2ef29ff3c83a3b9e3d3420df2a034b41a4a60dfc4237"
  end

  def install
    bin.install "pina-golada"
  end

  test do
    system "#{bin}/pina-golada version"
  end
end
