# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termshot < Formula
  desc "Creates screenshots based on terminal command output."
  homepage "https://github.com/homeport/termshot"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/termshot/releases/download/v0.2.2/termshot_0.2.2_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "1cfde4000f14c67860e11e64e673293ce9c31a821910784493c3b3fa02a5b00e"

      def install
        bin.install "termshot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/termshot/releases/download/v0.2.2/termshot_0.2.2_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b62fe4aaf6104c91a4062810892c999cd1d774e7f28443fda46c616a13e3eb9e"

      def install
        bin.install "termshot"
      end
    end
  end

  test do
    system "#{bin}/termshot --version"
  end
end
