# This file was generated by GoReleaser. DO NOT EDIT.
class Termshot < Formula
  desc "Creates screenshots based on terminal command output"
  homepage "https://github.com/homeport/termshot"
  version "0.1.0"
  license "MIT"

  if OS.mac?
    url "https://github.com/homeport/termshot/releases/download/v0.1.0/termshot_0.1.0_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "1862d31fa660d8cdbcc32fd050b9397a0668a84aad9950ea50ef83adb2869b5e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/homeport/termshot/releases/download/v0.1.0/termshot_0.1.0_linux_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "596135879c93e9a4ae290a029ae7db47ffd39cd9a79704fcaa1b034eaa033efb"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/homeport/termshot/releases/download/v0.1.0/termshot_0.1.0_linux_arm64.tar.gz", :using => CurlDownloadStrategy
    sha256 "88fcc83ecb3a7fe15e27e1f00d823cef04fac6d900e8b16835e1c37f650e83f0"
  end

  def install
    bin.install "termshot"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end

  test do
    system "#{bin}/termshot --version"
  end
end
