# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yft < Formula
  desc "yft - YAML file tool"
  homepage "https://github.com/homeport/yft"
  version "1.0.5"
  license "MIT"

  on_macos do
    url "https://github.com/homeport/yft/releases/download/v1.0.5/yft_1.0.5_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "2371f3181054de3af90227c181e8deedcd7ca458d6116e4e069aafcfacc98a94"

    def install
      bin.install "yft"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/homeport/yft/releases/download/v1.0.5/yft_1.0.5_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "9b9adf060a34f1cbe49d7f2f36fee6226464e637ddb96ce187d6408a495ef59d"

      def install
        bin.install "yft"
      end
    end
  end

  test do
    system "#{bin}/yft version"
  end
end
