# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yft < Formula
  desc "yft - YAML file tool"
  homepage "https://github.com/homeport/yft"
  version "1.0.4"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/homeport/yft/releases/download/v1.0.4/yft_1.0.4_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "a056877c0fb421d9bc6f870964e735b6fbfbb1a17c76f1efe48c7d9faaba65b6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/homeport/yft/releases/download/v1.0.4/yft_1.0.4_linux_amd64.tar.gz", :using => CurlDownloadStrategy
    sha256 "c254bb5e55bd9ab6efce0908e2ca0f8e7dde87570a24324baf40380080fcb835"
  end

  def install
    bin.install "yft"
  end

  test do
    system "#{bin}/yft version"
  end
end
